//! The plugin *registry release descriptor*: the JSON shape a registry
//! serves describing a published, downloadable build of a plugin's WASM
//! component. This module owns parsing and structural validation only —
//! like `crate::manifest`, it has no opinion on how a release becomes a
//! running Wasmtime component; that binding lives in `ryuzi-core`.
//!
//! Deliberately runtime-independent: no Wasmtime, no installer, no network
//! I/O. [`PluginRelease`] is data + validation only, mirroring
//! `crate::manifest::PluginManifest`'s discipline.

use serde::{Deserialize, Serialize};

/// A registry's release descriptor for a plugin: the concrete WIT API
/// version it was built against, where to fetch the component, and its
/// checksum. Served as JSON (unlike the TOML-authored
/// [`crate::manifest::PluginManifest`]) since it is generated by a
/// registry, not hand-authored by a plugin publisher.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PluginRelease {
    pub id: String,
    /// This release's version. Must parse as a [`semver::Version`].
    pub version: String,
    /// The exact WIT contract version this release's component was built
    /// against. Unlike a manifest's `[component] wit-api` (a range), this
    /// is a single concrete [`semver::Version`].
    #[serde(rename = "wit-api")]
    pub wit_api: String,
    pub component_url: String,
    pub component_sha256: String,
    #[serde(default)]
    pub size_bytes: Option<u64>,
    #[serde(default)]
    pub published_at: Option<String>,
}

/// Errors from parsing or validating a [`PluginRelease`].
#[derive(Debug, thiserror::Error)]
pub enum BundleError {
    #[error("invalid plugin release json: {0}")]
    Json(#[from] serde_json::Error),
    #[error("invalid plugin id: {0}")]
    InvalidId(String),
    #[error("invalid version {0:?}: {1}")]
    InvalidVersion(String, String),
    #[error("invalid wit-api version {0:?}: {1}")]
    InvalidWitApi(String, String),
    #[error("component_url must not be empty")]
    EmptyComponentUrl,
    #[error("component_sha256 must not be empty")]
    EmptyComponentSha256,
}

fn is_valid_id(id: &str) -> bool {
    let mut chars = id.chars();
    match chars.next() {
        Some(c) if c.is_ascii_lowercase() || c.is_ascii_digit() => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

impl PluginRelease {
    /// Parse JSON into a release descriptor and validate it in one step.
    pub fn from_json(input: &[u8]) -> Result<PluginRelease, BundleError> {
        let release: PluginRelease = serde_json::from_slice(input)?;
        release.validate()?;
        Ok(release)
    }

    /// Structural validation: id shape, `version` and `wit-api` semver
    /// parsing, and non-empty download coordinates.
    pub fn validate(&self) -> Result<(), BundleError> {
        if !is_valid_id(&self.id) {
            return Err(BundleError::InvalidId(self.id.clone()));
        }
        semver::Version::parse(&self.version)
            .map_err(|e| BundleError::InvalidVersion(self.version.clone(), e.to_string()))?;
        semver::Version::parse(&self.wit_api)
            .map_err(|e| BundleError::InvalidWitApi(self.wit_api.clone(), e.to_string()))?;
        if self.component_url.is_empty() {
            return Err(BundleError::EmptyComponentUrl);
        }
        if self.component_sha256.is_empty() {
            return Err(BundleError::EmptyComponentSha256);
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn valid_release_json() -> Vec<u8> {
        br#"{
            "id": "acme-connector",
            "version": "0.1.0",
            "wit-api": "0.1.0",
            "component_url": "https://registry.example.com/acme-connector/0.1.0/acme_connector.wasm",
            "component_sha256": "deadbeef",
            "size_bytes": 1024,
            "published_at": "2026-07-12T00:00:00Z"
        }"#
        .to_vec()
    }

    #[test]
    fn parses_a_valid_release() {
        let release =
            PluginRelease::from_json(&valid_release_json()).expect("valid release should parse");
        assert_eq!(release.id, "acme-connector");
        assert_eq!(release.version, "0.1.0");
        assert_eq!(release.wit_api, "0.1.0");
        assert_eq!(
            release.component_url,
            "https://registry.example.com/acme-connector/0.1.0/acme_connector.wasm"
        );
        assert_eq!(release.component_sha256, "deadbeef");
        assert_eq!(release.size_bytes, Some(1024));
        assert_eq!(
            release.published_at.as_deref(),
            Some("2026-07-12T00:00:00Z")
        );
    }

    #[test]
    fn release_size_bytes_and_published_at_are_optional() {
        let json = br#"{
            "id": "acme-connector",
            "version": "0.1.0",
            "wit-api": "0.1.0",
            "component_url": "https://registry.example.com/a.wasm",
            "component_sha256": "deadbeef"
        }"#;
        let release = PluginRelease::from_json(json).expect("minimal release should parse");
        assert_eq!(release.size_bytes, None);
        assert_eq!(release.published_at, None);
    }

    #[test]
    fn rejects_malformed_release_json() {
        let err =
            PluginRelease::from_json(b"not json").expect_err("malformed json should fail to parse");
        assert!(matches!(err, BundleError::Json(_)));
    }

    #[test]
    fn rejects_release_with_invalid_semver_version() {
        let json = br#"{
            "id": "acme-connector",
            "version": "not-a-version",
            "wit-api": "0.1.0",
            "component_url": "https://registry.example.com/a.wasm",
            "component_sha256": "deadbeef"
        }"#;
        let err = PluginRelease::from_json(json)
            .expect_err("invalid semver version should fail validation");
        assert!(matches!(err, BundleError::InvalidVersion(v, _) if v == "not-a-version"));
    }

    #[test]
    fn rejects_release_with_invalid_wit_api_version() {
        let json = br#"{
            "id": "acme-connector",
            "version": "0.1.0",
            "wit-api": "^0.1.0",
            "component_url": "https://registry.example.com/a.wasm",
            "component_sha256": "deadbeef"
        }"#;
        let err = PluginRelease::from_json(json)
            .expect_err("wit-api must be a concrete version, not a range");
        assert!(matches!(err, BundleError::InvalidWitApi(v, _) if v == "^0.1.0"));
    }

    #[test]
    fn rejects_release_with_empty_component_url() {
        let json = br#"{
            "id": "acme-connector",
            "version": "0.1.0",
            "wit-api": "0.1.0",
            "component_url": "",
            "component_sha256": "deadbeef"
        }"#;
        let err =
            PluginRelease::from_json(json).expect_err("empty component_url should fail validation");
        assert!(matches!(err, BundleError::EmptyComponentUrl));
    }

    #[test]
    fn rejects_release_with_empty_component_sha256() {
        let json = br#"{
            "id": "acme-connector",
            "version": "0.1.0",
            "wit-api": "0.1.0",
            "component_url": "https://registry.example.com/a.wasm",
            "component_sha256": ""
        }"#;
        let err = PluginRelease::from_json(json)
            .expect_err("empty component_sha256 should fail validation");
        assert!(matches!(err, BundleError::EmptyComponentSha256));
    }

    #[test]
    fn rejects_release_with_invalid_id() {
        let json = br#"{
            "id": "Acme Connector",
            "version": "0.1.0",
            "wit-api": "0.1.0",
            "component_url": "https://registry.example.com/a.wasm",
            "component_sha256": "deadbeef"
        }"#;
        let err = PluginRelease::from_json(json).expect_err("invalid id should fail validation");
        assert!(matches!(err, BundleError::InvalidId(id) if id == "Acme Connector"));
    }
}
